feat(document-request-post): 자료요청게시판 엔티티 설계
Sejong-Balsamic/Malsami-BE pull request #100
Opened 2024-10-02 15:16 UTC by minhong620

## 🛠 해결된 문제
--- 

## ✨ 주요 변경 사항
--- 

- DocumentRequestPost 엔티티 정의

## 📌 추가 변경 사항
---

## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-02 15:17 UTC, minhong620 commented
브랜치 이름 바꿨다가 날라갔네요,,
기존 pr은 #90 입니다

2024-10-04 06:47 UTC, Cassiiopeia requested changes
일단 브랜치 수정한거죠?

2024-10-04 06:47 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +  SOLUTION("해설");
이부분 예전에 코멘트했었음요

2024-10-04 06:47 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private List<DocumentType> documentType;
이부분 배열 지훈님꺼 참고

2024-10-04 06:47 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private String requestDepartment;
이부분도 예전에 코멘트 남김

2024-10-06 08:24 UTC, Cassiiopeia requested changes
아 ㅋㅋ 지훈님 코드였구만 ㅋㅋㅋ 무시할껀 무시해쥬세요 @Chuseok22

2024-10-06 08:24 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  // 자료 요청 학과
이거 교과목명 아닙니까? 자료요청학과는 뭘까유?

course course 여야하지않나요

2024-10-06 08:24 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  private Set<QuestionPresetTag> questionPresetTagSet = new HashSet<>();
이 부분 배열로해봅시다

2024-10-06 08:24 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +public enum DocumentType {
presetTag 어때요

2024-10-06 08:24 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/PostType.java
> +  QUESTION("질문글"),
이부분 제가 contentType으로 정의해놨옸습니다 합칠때 수정해야될것같긴해요

2024-10-06 08:24 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  private Integer reward = 0;
이거이름 바꿔야함 카톡에서 얘기했습니다

2024-10-06 08:24 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  // 질문게시글 정적 태그 추가
주석에 최대 2개라고 해주세요

배열로 바꾸면 거기에 맞는 로직 필요할듯

2024-10-07 11:38 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  // 자료 요청 학과
자기 학과 말고 다른 학과도 가능해서 순간 착각했었네요

2024-10-07 11:38 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  private Set<QuestionPresetTag> questionPresetTagSet = new HashSet<>();
hypersistence-utils 라이브러리 사용해서 구현했습니다

2024-10-07 13:12 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +public enum DocumentType {
아니면 DocumentCategory는 어떤가요

2024-10-07 13:22 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  private Set<QuestionPresetTag> questionPresetTagSet = new HashSet<>();
배열로 갈까하다가 기존의 Set을 유지했습니다
배열로 가면 중복 체크할 때도 Set을 이용하고 Exception도 늘어나서 Set으로 유지할게요 새찬님

2024-10-08 04:23 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  private Integer reward = 0;
넵 수정했습니다

2024-10-08 04:24 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +  // 질문게시글 정적 태그 추가
주석에 최대 2개 추가하겠습니다

2024-10-08 08:19 UTC, Chuseok22 commented
ContentType 클래스 메인에 푸시했습니다
PostType 부분만 ContentType으로 바꾸시면 될 것 같습니다!!
그리고 ErrorCode부분 한줄로 갈까요??

고생많으셨어요!!

2024-10-08 13:56 UTC, merged