feat(mongodb): MongoDB 여러 Document init
Sejong-Balsamic/Malsami-BE pull request #105
Opened 2024-10-04 06:08 UTC by Cassiiopeia

너무 내용이 많아 ㅈㅅ합니다 ㅎㅎ;

2024-10-05 05:21 UTC, Chuseok22 requested changes
바쁜데 고생많으셨어요!!

* 필드에서 연관관계 매핑할 때 UUID로 통일
* memberId 필드 @Indexed 추가
* enum 통일
* 경험치 증감 상황

2024-10-05 09:53 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/NoticeBoardLike.java
> +  private LikeType likeType; // POST, COMMENT
이거 밥먹다가 이해했습니다 ㅋㅋㅋㅋㅋㅋ
private UUID noticeId에 글pk, 댓글pk둘다 들어가도 상관없고 LikeType에서 해당 pk가 글에대한 좋아요인지 댓글에 대한 좋아요인지 구분 해주네요!!!
위에 리뷰는 무시하셔도 됩니다

2024-10-05 09:53 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentBoardLike.java
> +}
여기도 마찬가지로 어떤 로직인지 이해했습니다!! 위에 리뷰는 무시해주세요 ㅎㅎ

2024-10-05 12:01 UTC, minhong620 reviewed
수고하셨습니다~!

2024-10-05 13:26 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/BaseMongoEntity.java
> +public abstract class BaseMongoEntity {
> 기존에 pg에서 사용하던 BaseEntity이름은 그대로 가나요?

JPA 방식이랑 호환이안되는부분이 있는 부분이있어서 따로만들었어요 isDeleted 부분은 딱히 필요없을것같아서 제거했습니다.

2024-10-05 13:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/BaseMongoEntity.java
> +}
JPA의 @PreUpdate 는 MongoDB에서 불가능합니다

2024-10-05 13:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/NoticeBoardLike.java
> +  private UUID memberId;
추가할께유~~

2024-10-05 13:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionBoardLike.java
> +
수정하겠습니다~

2024-10-05 13:30 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/Report.java
> +  private String reportedPostId;  // 신고 대상 게시글 ID
네네ㅋㅋㅋ난리났구만

2024-10-05 13:30 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/Report.java
> +  private String reason;          // 신고 사유
네네 저부분 enum으로 수정하려고하긴합니다

2024-10-05 13:31 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/ActionType.java
> +  private final String description;
GPT행님의 무분별한 사용에 대한 검수과정에 문제가있네요 ㅎㅎ 수정하겠습니다.

2024-10-05 13:32 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/LikeType.java
> +  private final String description;
Comment가 Post는 아닌것같아서 따로뺴긴했거든요 흠.. 합칠까

2024-10-05 13:33 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/ReportType.java
> +}
> 얘는 PostType이랑 아예 같으니까 삭제하고 LikeType, PostType은 따로 가는거 어떠세요?

저는 이부분이 더 끌리긴합니다

이 enum은 완전겹치는군요? 이부분을 일단 postType으로 대체할께요

2024-10-05 13:33 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  CHANGE_POST_LEVEL,        // 게시글 등급 변경 시 엽전 소모
죄송합니다 검수를 또 ㅎㅎ;;; 저부분 삭제하겠습니다

2024-10-05 13:34 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  CREATE_POST,              // 게시글 작성 시 엽전 소모
맞아요 좀더 구체적으로 적겠습니다

2024-10-05 13:36 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  DELETE_POST,              // 게시글 삭제 시 엽전 환급
> 삭제 시 엽전 환급에 대해서는 논의해볼 필요가 있을 것 같아요 환급을 해주면 글을 올리는 것에 대한 리스크가 없어지는 것 같은데 대충 올려놓고 반응 별로네...? 하면 삭제해버리면 그만이니까

흠... 얘기봅시다

2024-10-05 13:38 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  DELETE_POST,              // 게시글 삭제 시 엽전 환급
> 혹시 YeopjeonAction이랑 YeopjeonConfig둘다 엽전 변동 이력에 사용되는 클래스인데 둘이 합칠 수 있는 방법이 있을까요??

없어보이긴합니다
합치려면 enum에 description, amount 이런식으로 여러개 추가해서 ( , , ) 이렇게 넣어서 관리하는건데 

그러면 Value로 Config로 따로 주입시켜서 관리시키는게아니라 정적으로 fix되어서 관리되어서 좋은 방법이 아닌것같아요

2024-10-05 13:39 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentBoardLike.java
> +}
s 마음에 안들어서 다 s로했다가 다 s뺏어요

2024-10-05 13:40 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/PurchaseHistory.java
> +  private UUID mediaFileId;
아아 맞네요 수정하겠습니다.

2024-10-05 13:40 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPostCustomTag.java
> +  private String questionPostId;
수정하겠습니다

2024-10-05 13:41 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/Report.java
> +  private UUID reporterId;      // 신고자 member ID
당하는사람인지 신고하는사람인지 구분할 필요가있다고 생각해서 reporterId로 했습니다

2024-10-05 13:42 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/ExpHistory.java
> +  @NotNull
밑에 두개를 사용해본적이없어서요 보통 create DB만들떄 not null 옵션을 붙이더라고요
일단 id같은 중요한 칼럼은 notnull 다시 붙여보겠습니다

2024-10-05 13:43 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/YeopjeonHistory.java
> +  private YeopjeonAction yeopjeonAction;    // 엽전 거래 유형
resultYeopjeon 말씀하시는거죠? 추가하겠습니다

2024-10-05 13:43 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +}
아아 오키요~~ 넵넵  추가하겠습니다

2024-10-05 13:43 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/repository/mongo/PointHistoryRepository.java
> +public interface PointHistoryRepository extends MongoRepository<YeopjeonHistory, String> {
어 이름이 이상하네요 수정하겠습니다

2024-10-07 04:07 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/LikeType.java
>    private final String description;
통일성있게 뒤에 게시글 쪽은 뒤에 POST붙일까요??
NOTICE_POST
DOCUMENT_POST
아니면 POST 다 빼는것도 나쁘지 않을 것 같아요
편한대로 부탁해요 ㅎㅎ

2024-10-07 04:07 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/PostType.java
LikeType과 완전히 동일한 enum클래스인데...
합치는 거 어떻게 생각하시나요??

2024-10-07 04:12 UTC, Chuseok22 reviewed
고생하셨어요!!

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/BaseMongoEntity.java
> +}
혹시 mongo 엔티티 수정여부는 서비스로직에서 수동으로 변경할 생각인가요??

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/ExpHistory.java
> +  private Integer exp;
총 경험치인지, 해당되는 action으로 변동되는 경험치인지 명확하게 해주면 좋을 것 같아요
totalExp, changedExp 요런식으로...? 어때요?

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/PurchaseHistory.java
> +  private Integer yeopjeonQuantity; // 소모한 엽전양
변동되는 부분 changed 처럼 직관적으로 보이는 단어로 바꾸는거 어때요?

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/YeopjeonHistory.java
> +  private Integer yeopjeon;         // 거래된 엽전 수 (양수: 획득, 음수: 소모)
변동되는 부분 통일된 단어를 사용하면 어떨까요?

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/ReportType.java
> +}
contentType이랑 합쳐도 괜찮을 것 같아요~

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  CHANGE_POST_LEVEL,        // 게시글 등급 변경 시 엽전 소모
CHANGE_POST_LEVEL 삭제부탁드려요

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  CREATE_POST,              // 게시글 작성 시 엽전 소모
여기도 CREATE_QUESTION_POST 로 수정하면 어때요?

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +  ACCEPT_ANSWER             // 답변 채택 시 엽전 획득
CHAETAEK_ANSWER~

2024-10-07 04:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +}
--민홍님이 수정 요청했던 부분--
1. 저작권법 위반 자료 신고시 엽전획득
2. 맨 처음 접속 시
3. 답변 채택한 글쓴이한테 엽전 지급

2024-10-07 13:48 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/YeopjeonAction.java
> +}
맞습니다 ㅎㅎ

2024-10-08 06:34 UTC, merged