feat(entity): MediaFile 엔티티 및 질문글, 답변글 이미지 파일 저장 로직 설계
Sejong-Balsamic/Malsami-BE pull request #112
Opened 2024-10-04 06:54 UTC by Chuseok22

## 🛠 해결된 문제
--- 

- 

## ✨ 주요 변경 사항
--- 

* 질문글, 답변글 이미지 파일 엔티티 설계
* 질문글, 답변글 이미지 파일 저장 로직 설계

## 📌 추가 변경 사항
---

## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-05 13:25 UTC, Cassiiopeia reviewed
로직 고칠게 많은데 일단 entity부터 만집시다 entity

2024-10-06 02:37 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/MediaFile.java
> +  private AnswerPost answerPost;
넵 ㅎㅎ 수정했습니다

2024-10-06 02:37 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/MediaFile.java
> +  private String filePath;
수정할게요

2024-10-06 02:38 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/util/S3Service.java
> +    String extension = getExtensionType(file);
음... 그러면 버킷이름 빼고 우선은 확장자 명으로 폴더 구분하겠습니다
추후에 더 좋은 방법으로 폴더 구분 할게요

2024-10-06 02:38 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/MediaFile.java
> +  private ExtensionType fileType;
넵

2024-10-06 08:29 UTC, Cassiiopeia requested changes
굿굿

2024-10-06 08:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/MediaFile.java
> +  private UUID questionId;
contentId 라고하는게 적절하지않나요?

2024-10-06 08:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/ExtensionType.java
> +  public static ExtensionType valueOfExtension(String extension) {
이게 왜필요할까요? MultipartFile에서 extension인가 fileType인가 MimeType 가져오는 메소드 없었었나? 

전 이거 여기에 description 말고 mimetype 으로 만들것같긴한데

그렇게 비교하는게 편하지않나요 Multipart도 파일이 들어가있는 객체니까 메타데이터가 여러개 들어있어요 아떤 메소드가 있는지 공부해보는것도 좋을듯요

2024-10-06 23:53 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/MediaFile.java
> +  private UUID questionId;
> contentId 라고하는게 적절하지않나요?

postId는 어때요?

2024-10-07 01:13 UTC, Cassiiopeia requested changes
한번 확인보세요

2024-10-07 01:13 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/ExtensionType.java
> +  public static Boolean isValidMimeType(String mimeType) {
이렇게 하면 매번 map을 만들고 list로 변환하고 선회해야하니까 리소스 낭비가있겠죠?

private static final Set<String> mimeTypes
를만들어서 클래스가 처음로드될때 한번만 실행되게하고 

이부분에 contains를 걸어서 확인해보는 로직으로 짜는게어때요

2024-10-07 01:13 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/util/S3Service.java
> +    return originalFilename.substring(originalFilename.lastIndexOf(".")); // 확장자 명
확장자가없는경우 이러면 에러 내뿜을것같은데

확장자가없을경우 빈문자열반환시킬까요? 

아니면 따로 예외처리

근데 

file.getContentType() 하면 MultipartFile에서 MIME타입 나올텐데 

이걸 그냥 애초에 

ExtensionType
이 enum 이름 

MimeType으로 바꾸고 

isValidMimeType(MulipartFile file){}

하면되는거아닌가요?

2024-10-07 04:13 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/ExtensionType.java
> +  public static Boolean isValidMimeType(String mimeType) {
넵 한번 해볼게요

2024-10-07 04:14 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/util/S3Service.java
> +    return originalFilename.substring(originalFilename.lastIndexOf(".")); // 확장자 명
그러면 extension말고 mime으로 전부 바꿔볼게요

2024-10-07 06:29 UTC, Cassiiopeia approved these changes
굿굿

2024-10-07 07:08 UTC, minhong620 reviewed
수고하셨습니다!

2024-10-07 07:09 UTC, merged