feat(service): 일간/주간 인기글 로직 작성 및 자료게시판 글 등록 로직 작성
Sejong-Balsamic/Malsami-BE pull request #136
Opened 2024-10-08 02:19 UTC by Chuseok22

## 🛠 해결된 문제
--- 

- 

## ✨ 주요 변경 사항
--- 

* 질문글 자료글 일간/주간 인기글 점수 계산 로직
* DocumentService 질문글 등록 로직
* 엔티티 필드명 통일

## 📌 추가 변경 사항
---

## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-08 13:13 UTC, minhong620 reviewed
수고하셨습니다!!

2024-10-08 13:13 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/repository/postgres/QuestionPostRepository.java
> +  // 일간 인기글 계산 (글 작성일이 startDate 보다 나중인 질문 게시글)
괄호 안에 텍스트만 있어도 될 것 같아요

2024-10-08 13:13 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/repository/postgres/MediaFileRepository.java
> +  @Query("SELECT COUNT(m) FROM MediaFile m WHERE m.postId = :postId AND m.postType = 'QUESTION'")
ContentType으로 수정해야할 것 같아요

2024-10-08 13:13 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/repository/postgres/MediaFileRepository.java
> +  @Query("SELECT COUNT(m) FROM MediaFile m WHERE m.postId = :postId AND m.postType = 'ANSWER'")
@Query("SELECT COUNT(m) FROM MediaFile m WHERE m.postId = :postId AND m.contentType = :contentType")
int countByPost(UUID postId, ContentType contentType);
이렇게 하면 질문, 답변 한번에 가능하네용

2024-10-10 00:12 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionPostService.java
> +    List<QuestionPost> posts = questionPostRepository.findQuestionPostsAfter(yesterday);
일간은 매일 자정마다 갱신, 주간은 월요일 자정마다 갱신이라 스케줄러 2개 사용했습니당

2024-10-11 05:13 UTC, minhong620 reviewed
수고하셨습니다!!

2024-10-11 05:13 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +    // 캐시 갱신
스케줄러 사용도 고려해볼 수 있을 것 같습니다

2024-10-11 06:30 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostController.java
> +  public ResponseEntity<List<DocumentPostDto>> getWeeklyPopularDocumentPost(DocumentPostCommand command) {
감사합니다!!

2024-10-11 06:30 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostControllerDocs.java
> +          - 요청 시각으로부터 24시간 이내에 작성된 상위 30개의 일간 인기글을 조회합니다.
좋아요~ 그러면 20개로 수정할게요

2024-10-11 06:41 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPostCustomTag.java
> +  @NotNull
questionPostId 말씀하시는건가용?? 아니면 customTag??
customTag가 태그 내용인데 null 이면 안될 것 같은디...
커스텀 태그 설정 안하는건 되는데 null로 설정하는건 안되게 하는게 맞을 것 같아요

2024-10-11 06:47 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +  public static final String DAILY_QUESTION_POSTS_KEY = "'dailyPopularQuestionPosts'";
찾아보니까 @Cacheable(key = "문자열")에서 사용할 때는 작은 따옴표 있어야하는데 상수로 선언해서 사용할 때는 없어도 괜찮다고 하네요 ㅎㅎ 수정하겠습니다

2024-10-11 06:49 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +    // 캐시 갱신
리뷰하신 메서드 이미 스케줄러 사용하고있어요
public void calculateDailyScore 부분 맞죠?

2024-10-13 05:55 UTC, Cassiiopeia requested changes
어우 너무많다

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostController.java
> +public class DocumentPostController implements DocumentPostControllerDocs {
이거 들어가는 내용이 비슷할것같아서

질문답변게시판 Dto Command 만들어서 통합해하는건 어떻게 생각합니까

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostControllerDocs.java
> +            _예: "컴퓨터구조"_
과목명?

교과목명 말하는건가요?

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostControllerDocs.java
> +          - 글 제목, 본문, 과목명은 null 값이 들어갈 수 없습니다. (required)
영어로 required보다 

필수항목 이라고 한국어로 표현하는거 어떱니까 ㅋㅋ

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostControllerDocs.java
> +          - 요청 시각으로부터 24시간 이내에 작성된 상위 30개의 일간 인기글을 조회합니다.
이거 요청한시각이 아니라 요청한 날짜 전날 00:00(자정) 기준? 이런거 있지않았아요? 더. 확실하게 알려줍시다

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/AnswerPostService.java
> +        .isChaetaek(command.getIsChaetaek() != null ? command.getIsChaetaek() : false)
생성할때는 무조건 false

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/DocumentPostService.java
> +  public DocumentPostDto saveDocumentPost(DocumentPostCommand command) {
QuestionBoardCommand, QuesetionBoardDto 만들어서 통합 관리하는거 어때요

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +  }
이런 점수계산 로직 
따로뻅시다 Config랑 관련된것같은데
ScoreConfig로 뺴서 

나중에 중앙에서 한번에 바꾸면 딲딲딲 바꿀수있게 

지금 3,2 이렇게 하드코딩해두면 나중에 유지보수가안돼요

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +  }
이런것도 따로 Util에 ScoreCalculator 만들어서 점수계산 로직 관리해도괜찮을것같고

이런 계산 로직 겹칠수도있으니까 

자료도 점수계산하잖아유

같진않겠지만 모아두면좋을것같은데 가시성도좋고

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +  }
util쪽에 중앙메소드 하나 만들어서 사용해서씁시다

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/MediaFileService.java
> +    }
S3 service에서 메소드에서 에러 throw하나요?

굳이 그래야할까요S3Serivice안에서 에러코드 내보내면안돼요?
지금 . 이MediaFileService에서 throw new CustomException(ErrorCode.FILE_UPLOAD_ERROR); 이런 에러 메시지 내보내는거면 그냥 S3Service에서 처리하는게 더 좋아보임

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/MediaFileService.java
> +  }
이거 잘 이해못했는데

mediaFile 1개만 만드는 로직인거죠?

왜 굳이?

여기에 Dto Command가 왜있을까요 굳이 있을 필요는없고 

이건 유틸 느낌이 강한 class라서

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionPostCustomTagService.java
> +    }
4 이것도 static 으로 위로뻅시다

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionPostCustomTagService.java
> +    }
10자제한도 위로뻅시다

2024-10-13 05:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionPostCustomTagService.java
> +      return tag; // 저장된 태그 반환
이거그냥 return문에서 한번에 표현합시다

2024-10-14 00:35 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostControllerDocs.java
> +          - 요청 시각으로부터 24시간 이내에 작성된 상위 30개의 일간 인기글을 조회합니다.
이 부분은 금요일 회의 때 로직 바뀌어서 민홍님께서 수정해주실 거에요

2024-10-14 00:47 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/MimeType.java
> +        .filter(type -> type.getMimeType().equalsIgnoreCase(mimeType))
찾아보니까 대소문자 구분 없이 단순히 문자열을 비교하는 과정이면 equalsIgnoreCase가 더 메모리 사용도 적다고하네요
우선 기존처럼 IgnoreCase로 하는거 어때요??

2024-10-14 02:01 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/DocumentPostController.java
> +public class DocumentPostController implements DocumentPostControllerDocs {
이거 브랜치 따로 파서 작업할게요

2024-10-14 02:02 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/PopularPostService.java
> +  }
요것도 따로 브랜치 만들어서 작업하겠습니다

2024-10-14 04:07 UTC, Cassiiopeia requested changes
전체적으로 한 종류의 POST 요청이라서 부득이하게 알려주는 말이 url 에 들어가야합니다

#25  참고해주셔요

2024-10-14 04:07 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/AnswerPostController.java
> +  @PostMapping(value = "", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
왜 없애버림요

저장한다는 말있어야될것같아요

전체적으로 한 종류의 http 요청이기때문에

2024-10-14 04:14 UTC, merged