refactor(question, document): 질문, 답변 command, dto 통합
Sejong-Balsamic/Malsami-BE pull request #154
Opened 2024-10-14 05:36 UTC by Chuseok22

## ✨ 변경 사항
--- 

* 질문, 답변 command, dto 통합 -> QuestionDto, QuestionCommand
* 자료, 자료요청 command, dto 통합 -> DocumentDto, DocumentCommand
* dto, command 변경에 따른 service, controller 수정

## ✅ 테스트
---
- [x] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-14 06:01 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionDto.java
> +  private List<MediaFileDto> mediaFiles; // 질문, 답변
이 부분 List<MediaFile> mediaFiles 로 수정했습니다

2024-10-14 08:03 UTC, Cassiiopeia requested changes

2024-10-14 08:03 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/util/config/ScoreConfig.java
> +@Configuration
스프링 어노테이션 실수로 쓴건지 아님.. 흠..

ScoreConfig 라는의미로 말했던건 다른의미긴했거든요

지금 작성한건 로직이구

흠... Configuration 어노테이션이랑 Service Component 어노테이션에 대해서 알아봐주세요

2024-10-15 08:46 UTC, Cassiiopeia approved these changes
굿굿

2024-10-15 08:56 UTC, merged