feat(service): 질문 게시글, 답변 좋아요 로직
Sejong-Balsamic/Malsami-BE pull request #180
Opened 2024-10-17 08:12 UTC by Chuseok22

## ✨ 변경 사항
--- 

## ✅ 테스트
---
- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-17 13:55 UTC, Cassiiopeia requested changes

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/postgres/Yeopjeon.java
> +  public void changeResultYeopjeon(int resultYeopjeon) {
update

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    }
프론트한테서
ContentType을 따로 받아서 하는게 좋아보입니다

굳이 두 repo를 검색할 필요가없어보여요

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    yeopjeonService.updateYeopjeon(member, YeopjeonAction.SEND_LIKE);
좋아요 누른사람은 엽전개수가 증가하는게 아니라 경험치 증가

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +  }
일단 경험치랑 엽전 증가에 대해서는 비동기식으로 따로해야하는게 사용자 편의성을 봐서 좋을것같고

게시글 좋아요 증가랑 좋아요 mongoDB증가는 동기식으로하고 반환합시다
로깅처리 해주세요 모든 로그는 member table의 uuid 말고 member.studentID로 해볼까요

monogDB에 대해서 한번에 입력하면안되고

DB가 다르니까 일관성을 확인하기위한 방어로직이 필요해요 메소드로 따로 분리해서 try catch 해야할수도있구요

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +      yeopjeon.changeResultYeopjeon(0);
엽전 -도있으니까 음수 엽전도 허용 나쁘지않을지도?

-인데 엽전을 사용할때 예외처리하면 좋을것같아요

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +        .orElseThrow(() -> new CustomException(ErrorCode.MEMBER_YEOPJEON_NOT_FOUND))
YEOPJEON_NOT_FOUND 가 맞을듯요

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  public int getResultYeopjeon(Member member) {
dto반환 지켜주세요

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  public void updateYeopjeon(Member member, YeopjeonAction action) {
이건 왜 void죠?

2024-10-17 13:55 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/util/config/YeopjeonConfig.java
Integer

2024-10-18 02:15 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    }
그러면 프론트에서 QuestionId랑 ContentType 받아올게요
지금 구현한거는 QuestionId만 받았어요

2024-10-18 02:24 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    yeopjeonService.updateYeopjeon(member, YeopjeonAction.SEND_LIKE);
감사합니당~

2024-10-18 02:25 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +      yeopjeon.changeResultYeopjeon(0);
마이너스 통장이라 ㅋㅋㅋㅋ 한번 상의해봐용

2024-10-18 17:20 UTC, Cassiiopeia approved these changes

2024-10-18 17:20 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonHistoryService.java
> +  public void addYeopjeonHistory(Member member, YeopjeonAction action) {
save어떠요? 이거 다른곳에서 어떻게 메소드이름지었었죠?

2024-10-18 17:20 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  }
엽전을 사용할때에는 엽전이 부족하면 아예 트랜잭션이 안일어나야될것같아요

update랑 사용하는건 다른 개념인가요?

2024-10-18 17:20 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +      throw new CustomException(ErrorCode.INVALID_REQUEST);
더 구제척인 에러코드가 필요할듯요 

INVALID_CONTENT_TYPE 라던지

2024-10-18 17:20 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +        yeopjeonDto.getYeopjeon().getResultYeopjeon());
로깅 기능이 yeopjeonService updateYeopjeon안에 있음 어떨까 YeopjeonDto yeopjeonDto = 이부분이 현재로써는 필요없는것같기도하고요

2024-10-18 17:20 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    yeopjeonHistoryService.addYeopjeonHistory(writer, YeopjeonAction.RECEIVE_LIKE);
이것처럼

2024-10-21 07:37 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  }
애초에 엽전 사용할 때 부족하면 오류 던지고
사용하다가 문제 생기면 transaction 일어나고 이렇게 가자는 말이죵??

2024-10-23 00:34 UTC, Cassiiopeia requested changes

2024-10-23 00:34 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/LandingController.java
> +  @LogMonitoringInvocation
Async에는 LogMonitoringInvocation 작동 안해요 참고해요

2024-10-23 00:34 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/LandingControllerDocs.java
> +          **입력 파라미터 값:**
입력파라미터 없는데 왜 command받아요? 

pagable에 활용하려면 입력파라미터 받는거 있어야되거든요?

그거 명시해준다음에 기본값도 알려줍시다

2024-10-23 00:34 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/LandingControllerDocs.java
> +          없음
위와 동일

2024-10-23 00:34 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    }
굳이 또 선회해야할까요 위에서 else if 에 대해서 increaseLikeCount하면되지않을까요?

2024-10-23 00:34 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +      yeopjeonDto = yeopjeonHistoryService.saveYeopjeonHistory(writer, YeopjeonAction.RECEIVE_LIKE);
yeopjeonDto 이게 필요할까요?

2024-10-23 01:36 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    }
65~70번째 줄에서 본인이 본인글에 좋아요 누르는 경우 검증한 뒤에 좋아요 증가시키려고 이렇게 작성했어요

2024-10-23 01:43 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +      yeopjeonDto = yeopjeonHistoryService.saveYeopjeonHistory(writer, YeopjeonAction.RECEIVE_LIKE);
보상로직 실행될 때 이미 저장된 엽전 히스토리 내역을 삭제해야해서 그때 사용돼요

2024-10-23 07:56 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/LandingControllerDocs.java
> +          **입력 파라미터 값:**
수정했습니다

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/repository/postgres/QuestionPostRepository.java
> +  List<QuestionPost> findOrderByWeeklyScoreDescAndCreatedDateAfter(@Param("lastWeek") LocalDateTime lastWeek, Pageable pageable);
Pageable 이렇게 쓰는거 아닙니다
 
 파라미터 3개 받을수있는 객체이구요

List를 반환하는거아닙니다 

더자세히는 말안할꺼구요 Pagable은 한번 알면 좋으니까 공부해보셔요

완~ 전 간결하게 적을수있거든요

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    }
아뭔가 저는 이거 

    // 로그인 된 사용자와 작성자가 같은 경우 좋아요 불가
    if (member.getMemberId().equals(writer.getMemberId())) {
      log.error("본인 글에 좋아요를 누를 수 없습니다. 로그인된 사용자: {}, 글 작성자: {}",
          member.getStudentId(), writer.getStudentId());
      throw new CustomException(ErrorCode.SELF_ACTION_NOT_ALLOWED);
    }
    
이걸 따로 메소드로 뺴고
    
    
    // 해당 글 좋아요 증가
    if (command.getContentType().equals(ContentType.QUESTION)) {
      questionPost = questionPostRepository.findById(postId)
          .orElseThrow(() -> new CustomException(ErrorCode.QUESTION_POST_NOT_FOUND));
      writer = questionPost.getMember();
    } else if (command.getContentType().equals(ContentType.ANSWER)) {
      answerPost = answerPostRepository.findById(postId)
          .orElseThrow(() -> new CustomException(ErrorCode.ANSWER_POST_NOT_FOUND));
      writer = answerPost.getMember();
    } else {
      throw new CustomException(ErrorCode.INVALID_CONTENT_TYPE);
    }
    

여기안에서 Member 같은지 확인하고 각각 increaseLike할것같습니다 

굳이 한번돌고 

member확인하고 또도는 과정이 직관적이지가 않아서

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +      }
아 이런식으로 계속 체크하는구나

흠... 아뭔가 지저분한것같기도하면서 어쩔수없는것같기도하고 ㅋㅋ

로직은 맞아서 ㅋㅋ

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonHistoryService.java
> +  }
이거 굳이?

그냥 yeopjeonHistory 이거 반환해요 굳이 DTO로 감쌀 필요없어보임
public yeopjeonHistory saveYeopjeonHistory(파라미터들)

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +      yeopjeon.updateResultYeopjeon(0);  // 엽전 개수를 0으로 설정
0으로 설정하면안되죠

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +    int updateYeopjeon = yeopjeon.getResultYeopjeon() + yeopjeonCalculator.calculateYeopjeon(action);
updateYeopjeon 보다는 calculatedYeopjeon 이라던지가 더 와닿긴해요

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  public void updateYeopjeon(Member member, YeopjeonAction action) {
updateYeopjeon 하고 calculateYeopjeon 하고 변수이름만 보면 차이점을 모르겠어요

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  }
이것도 Dto말고 yeopjeon 만 반환하죠

살짝 이것도 util감이 있어서 굳이 감쌀 이유는 없어보여요

짭히 계속 까서 써야되는거잖아요? 그래서 ㅇㅇ

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +}
궁금한데 언제쓰는거예요?

위에서 쓴거보긴했는데... 끝에오니까 집중력이 ㅎㅎ

2024-10-23 17:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/util/config/WebSecurityConfig.java
> +                .requestMatchers(HttpMethod.POST, "/api/landing/popular/**").permitAll()
이거 굳이안써도돼요

2024-10-24 00:48 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/repository/postgres/QuestionPostRepository.java
> +  List<QuestionPost> findOrderByWeeklyScoreDescAndCreatedDateAfter(@Param("lastWeek") LocalDateTime lastWeek, Pageable pageable);
넵 수정했습니다

2024-10-24 01:05 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +      }
ㅠㅠ 앞으로 작성하는 로직들...ㅋㅋ 걱정이되네요

2024-10-24 01:06 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/QuestionBoardLikeService.java
> +    }
수정했습니다!! 훨씬 좋네요

2024-10-24 01:13 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +      yeopjeon.updateResultYeopjeon(0);  // 엽전 개수를 0으로 설정
와...완전 바보였다 감사합니다

2024-10-24 01:15 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  public void updateYeopjeon(Member member, YeopjeonAction action) {
updateYeopjeon은 Yeopjeon action에 따라 사용자의 엽전 개수를 바꾸는 메서드에요
calculateYeopjeon은 해당 action을 yeopjeonConfig에서 찾아서 증/감 개수만 반환해주는 메서드에요

음... 좀 더 명확한 변수명으로 수정해보겠습니다

2024-10-24 01:16 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +  }
Yeopjeon, YeopjeonHistory이쪽은 사용자한테 반환하는 값들이 아니니까 Dto 전부다 삭제하겠습니다~~

2024-10-24 01:33 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/YeopjeonService.java
> +}
보상로직에서 사용돼요
`    // 좋아요 받은 사용자 엽전 개수 증가 - A
    yeopjeonService.updateMemberYeopjeon(writer, YeopjeonAction.RECEIVE_LIKE);

    YeopjeonHistory yeopjeonHistory;
    try {
      // 엽전 히스토리 내역 추가(MongoDB) - B
      yeopjeonHistory = yeopjeonHistoryService.saveYeopjeonHistory(writer, YeopjeonAction.RECEIVE_LIKE);
    } catch (Exception e) {
      log.error("엽전 히스토리 저장 실패 및 롤백: {}", e.getMessage());

      // 좋아요 수 롤백
      if (questionPost != null) {
        questionPost.decreaseLikeCount();
      } else {
        answerPost.decreaseLikeCount();
      }
      // 보상 로직: 엽전 수 롤백 - B 실패 시 A 롤백
      yeopjeonService.rollbackYeopjeon(writer, YeopjeonAction.RECEIVE_LIKE);
      throw new CustomException(ErrorCode.YEOPJEON_HISTORY_SAVE_ERROR);
    }`

updateMemberYeopjeon을 통해서 좋아요를 받은 사용자의 엽전 개수를 증가(PG)시킨 뒤, 히스토리를 저장(Mongo)하는 도중 문제가 발생할 경우 rollbackYeopjeon메서드를 통해서 PG에서 증가시킨 엽전 개수를 롤백합니다

2024-10-24 01:34 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/util/config/WebSecurityConfig.java
> +                .requestMatchers(HttpMethod.POST, "/api/landing/popular/**").permitAll()
아하 삭제하겠습니다

2024-10-28 05:50 UTC, merged