fix(question-post): 질문게시판 엔티티 수정
Sejong-Balsamic/Malsami-BE pull request #32
Opened 2024-09-23 01:18 UTC by Chuseok22

## 🛠 해결된 문제
--- 

- 

## ✨ 주요 변경 사항
--- 

## 📌 추가 변경 사항
---

## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-09-23 01:29 UTC, Cassiiopeia requested changes
굿굿

2024-09-23 01:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +    private int answerCount = 0;
변수이름을 보아하니 이건 답변수같은디용?

댓글수도 다뤄주세요

2024-09-23 01:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +@Builder
@Superbuilder  어때요??

한번 찾아볼까요

isDeleted를 건들일수가있어서 수정해야핡서같아요

2024-09-23 01:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +@ToString
ToString( 그 super 옵션값 enable하죠

이것도 superbuilder 랑 비슷한의미

2024-09-23 01:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +    @JoinColumn(name = "member_id")
JoinColum 넣으면 좀 헷갈릴수도있어요이거

Member 에 내가알기로 id 가 memberId 인데

JoinColumn으로 member_member_id 인것을 
member_id 로 임의로 지정하는거니까

이거 좀 고민인데

id에 entity이름을 넣을지 말지에 따라서 
JoinColumn에서 id명시하는게 달라져야할듯요

일단 id 이름에 entity정보 넣는순간

member_member_id 가 default 일꺼예요

2024-09-23 01:29 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +}
우리 더 있지않았나요

예를 들면.. 수정됨 표시

isEdited() 아 물론 BaseTimeEntity를 통해서 

createdAt과 updatedAt시간이 다르면 
알수도있지만

isEdited true를 보면 프론트가 더 알기쉽겠죠

피그마를 안봐서 기억이 가물가물하구만

2024-09-23 01:57 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +@ToString
@ToString(callSuper = true) 이거 말하는거죠?

2024-09-23 01:57 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +    @JoinColumn(name = "member_id")
그럼 JoinColumn 사용하지말고 그냥 이름 설정해주는대로 갈까요?

2024-09-23 02:09 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +}
그러면 basetimeentity에 isEdited 값을 넣는 건 어때요??
질문 게시글, 답변, 댓글
자료 게시글, 답변, 댓글 수정할 수 있으면 각각 엔티티에 넣는 것 보다 createdAt updatedAt 다르면 isEdited값 true로 설정하게 만들면 될 것 같은데

2024-09-23 02:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +    @JoinColumn(name = "member_id")
> 그럼 JoinColumn 사용하지말고 그냥 이름 설정해주는대로 갈까요?

저같으면 그럴듯요

2024-09-23 02:19 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/QuestionPost.java
> +}
> 그러면 basetimeentity에 isEdited 값을 넣는 건 어때요?? 질문 게시글, 답변, 댓글 자료 게시글, 답변, 댓글 수정할 수 있으면 각각 엔티티에 넣는 것 보다 createdAt updatedAt 다르면 isEdited값 true로 설정하게 만들면 될 것 같은데

좋은 생각이군요

updatedAt 이 업데이트될때 

isEdited 가 true 로 바뀔수있는 방법을 고안해봅시다

찾으면 바로나올듯

2024-09-24 01:23 UTC, Cassiiopeia requested changes

2024-09-24 01:23 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/BaseTimeEntity.java
> +  private Boolean isReported = false;
신고여부는 애매한것같은데요

여러명이 신고할수가있어서 

신고당했는지 안당했는지는 의미가 없을것같습니다

이거 baseEntity로 이름을 바꿀까요??

시간관련되어있는 요소만 있는게 아니네 생각해보니가

2024-09-24 01:23 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/BaseTimeEntity.java
> +  }
신고도 마찬가지

2024-09-24 01:49 UTC, merged