feat(docmunet-post): 자료게시판 엔티티 설계
Sejong-Balsamic/Malsami-BE pull request #36
Opened 2024-09-24 05:04 UTC by minhong620

## 🛠 해결된 문제
--- 

## ✨ 주요 변경 사항
--- 

- DocumentPost 엔티티 정의
## 📌 추가 변경 사항
---

- 없음
## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-09-25 01:55 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +@Setter
builder있으니까 setter 어노테이션 제거해도 될 것 같아요!!

2024-09-25 01:55 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/Grade.java
> +  천민,
한글로 바로 정의하는 것 보다 KING 이런식으로 만들고, 생성자 통해서 description 사용하는게 좋을 것 같아요!!

2024-09-25 04:50 UTC, Cassiiopeia requested changes

2024-09-25 04:50 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  private Grade grade = Grade.천민; // 게시물 등급
이거 한국어로 하지맙시다

제가만든 Author enum 클래스 참고해주세요

2024-09-25 04:50 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  @Builder.Default
싫어요도 있어야함

2024-09-25 04:50 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +}
이거 무조건 공개아니였음요?

2024-09-25 04:50 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  private String writer;  // 작성자
writer보다 Author라는 표현을 더 많이쓰지않나요?

그리고 Member가있는데 왜 writer가 또있나요?

2024-09-25 04:50 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/Grade.java
> +  천민,
동의 어 보감요

2024-09-25 05:26 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +}
이게 자료게시판 글작성에서는 닉네임은 무조건 보이고, 비공개할 수 있는 건 학과만 가능

2024-09-25 05:27 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +@Setter
command, dto 모두 builder사용하니까 setter 제거하자고 하네요

2024-09-25 05:36 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  private String writer;  // 작성자
이거 프론트에서 받아오는 값이 아니라 단순히 백에서 member 매핑한 정보 가지고 writer넣어줄 수 있어서 삭제해도 괜찮을 것 같아요

2024-09-26 00:58 UTC, Chuseok22 commented
굳굳

2024-09-26 01:44 UTC, Chuseok22 commented
새찬님이 한번 보신대요

2024-09-26 01:54 UTC, Cassiiopeia requested changes
협의해봅시다

2024-09-26 01:54 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  private Boolean isDepartmentPrivate = false; // 내 학과 비공개
보통이제 학과는 major라는 표현쓰지않나요?

2024-09-26 01:54 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  private int likeCount = 0; // 추천수
Integer 래퍼클래스로

2024-09-26 01:54 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
> +  private int downloadCount = 0; // 다운로드수
다 레퍼클래스로 바꿔줘요 int -> Integer

2024-09-26 01:54 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/Grade.java
> +}
이 Grade라는 표현이 좀 안와닿는데요

Grade는 성적아닌가요??

롤티어 레이팅처럼

PostTier 라던지 DocumentPostTier 라던지 

저 영어로 쓴것도 안와닿음

Noble? 흠 조선시대 변수인데 유럽냄새 나서 뭔가 그냥 

Cheonmin Jungin Yangban King

저같으면 이렇게 할것같은데

2024-09-26 02:11 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
>    @Builder.Default
Enum 저장형식 String으로 해주셔야 DB에 숫자로 저장 안돼요

2024-09-26 02:19 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentPost.java
>    @Builder.Default
@Enumerated(EnumType.STRING) 요거 쓰시면 돼요

2024-09-26 02:56 UTC, merged