feat(comment): 댓글 엔티티 및 댓글 등록 로직 작성
Sejong-Balsamic/Malsami-BE pull request #89
Opened 2024-09-30 07:45 UTC by Chuseok22

## 🛠 해결된 문제
--- 

- 

## ✨ 주요 변경 사항
--- 

* 댓글 엔티티 설계
* 댓글 작성 controller 설계
* 댓글 작성 service 로직 설계

## 📌 추가 변경 사항
---

## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-02 03:27 UTC, Cassiiopeia requested changes
DOCS 오류있으면안돼요

프론트가 이것만본다는걸 생각해야함

2024-10-02 03:27 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/CommentController.java
> +    return ResponseEntity.ok(commentDto);
이거 합쳐줄수있나유 포맷 통일합시다

2024-10-02 03:27 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/controller/CommentControllerDocs.java
> +          - **DOCUMENT_REQUIRED** (자료요청글)
피그마보면 Request입니다

2024-10-02 03:27 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/Comment.java
> +  private UUID commentId;
이거 아닐텐데
이건 SPIRNG에서 UUID생성해서 보내는 로직 아닌가요??
같은방식으로 생성하는지 모르겠네

제가 썼던 방식은 확실히 DB단에서 자동으로 생성되게 해놓는거거든요?

@GeneratedValue(strategy = GenerationType.AUTO)
이 부분은 어떤식으로 작동하는지 모르겠음

찾아서 공지 부탁드려요

2024-10-02 03:27 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/service/CommentService.java
> +
하지말라니까~


.isPrivate(command.getIsPrivate())
이부분을 
command.getIsPrivate() != null) ? command.getIsPrivate() : false
저같음 이런식으로 넣겠소

2024-10-02 07:04 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/CommentController.java
> +    return ResponseEntity.ok(commentDto);
ok

2024-10-02 07:04 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/controller/CommentControllerDocs.java
> +          - **DOCUMENT_REQUIRED** (자료요청글)
감사합니다

2024-10-02 13:54 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/service/CommentService.java
> +
@Builder.Default
  private Boolean isPrivate = false;
이렇게 선언해서 null값이 안되는 줄 알았는데 아니군요

2024-10-02 14:34 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/Comment.java
> +  private UUID commentId;
pg에서는GenerationType.AUTO가 GenerationType.SEQUENCE를 선택한다고 하네요

GenerationType.SEQUENCE:
데이터베이스에서 시퀀스 객체를 사용하여 ID 값을 생성한다. 주로 Oracle, PostgreSQL에서 사용된다.
JPA는 미리 시퀀스를 사용해 ID 값을 가져온 후, 엔티티를 삽입한다.
이 전략은 데이터베이스에 독립적인 시퀀스 관리가 필요할 때 유용하다.

@GeneratedValue(strategy = GenerationType.AUTO)랑 @Column(columnDefinition = "uuid DEFAULT uuid_generate_v4()", updatable = false)이랑 중복된 설정이라 @GeneratedValue 생략해도 될 것 같습니다

2024-10-04 00:14 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/service/CommentService.java
> +
null 값 되는건 맞아요!! 새찬님께서 @Builder.default 어노테이션 붙인 필드도 초기값 모두 명시적으로 넣자고 하셨어요

2024-10-04 02:00 UTC, merged