feat(document-request-post): 자료요청게시판 엔티티 설계
Sejong-Balsamic/Malsami-BE pull request #90
Opened 2024-10-01 02:41 UTC by minhong620

## 🛠 해결된 문제
--- 

- 

## ✨ 주요 변경 사항
--- 

## 📌 추가 변경 사항
---

## ✅ 테스트
---

- [ ] 수동 테스트 완료
- [ ] 테스트 코드 완료

2024-10-02 00:06 UTC, Chuseok22 requested changes
고생하셨어요!!

2024-10-02 00:06 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +  PAST("기출"),
요거 기출문제 영어로 past라고 하나요??
past_exam, past_test, previous_exam, previous_test, zocbo ㅋㅋㅋ
다같이 한번 상의해보면 좋을 것 같아요!!

2024-10-02 03:42 UTC, Cassiiopeia requested changes
고생하셨습니다요

2024-10-02 03:42 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +  PAST("기출"),
강의 자료: 필기 자료, 교안, 녹화본, 실험/실습 자료
과제 기출: 퀴즈, 기출 문제
해설: 솔루션, 족보

이렇게 지금 figma에 적혀있거든요?

이거 description에 추가해주시고

GPT 추천값 
    // 간단한 ENUM 값
    LECTURE_MATERIAL("Lecture Material"),
    PAST_EXAM("Past Exam"),
    SOLUTION("Solution");

2024-10-02 03:42 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private String requestDepartment;
이거 Enum아니고 Course 아닙니까?
@ManyToOne

2024-10-02 03:42 UTC, Cassiiopeia commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private List<DocumentType> documentType;
이거 중복된거 들어가도됩니까??

그냥 단일이 아닌가요?

2024-10-02 14:38 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private List<DocumentType> documentType;
배열로 수정해보겠습니다!

2024-10-02 14:38 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private List<DocumentType> documentType;
배열로 수정해보겠습니다!

2024-10-02 14:47 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private String requestDepartment;
네 Course의 학과와 엮겠습니다!

2024-10-02 14:53 UTC, minhong620 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +  PAST("기출"),
DOCUMENT("자료: 필기 자료, 교안, 녹화본, 실험/실습 자료") // DocumentPost로 가고있어서요
PAST_EXAM("기출: 퀴즈, 기출 문제, 과제") // 기출이라는 단어만 써서 포괄적인게 나은 것 같습니다
SOLUTION("해설: 솔루션") // 족보라는 단어는 안보이는게 나을 것 같아서 삭제했습니다 ㅋㅋ
다들 어떻게 생각하시나요

2024-10-02 15:11 UTC, closed without merging

2024-10-04 04:32 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/constants/DocumentType.java
> +  PAST("기출"),
좋아요!!

2024-10-04 04:35 UTC, Chuseok22 commented on src/main/java/com/balsamic/sejongmalsami/object/DocumentRequestPost.java
> +  private List<DocumentType> documentType;
Set<DocumentType>하시면 될거에요 ㅎㅎ HashSet<DocumentType> 사용하면 중복 된 값은 들어갈 수 없게 만들 수 있어요